### ISSUE TITLE
SSL certificates on twine-together domains

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/hq#27]
@SonjaTwine 

I've tried to setup SSL certificates on the `.twine-together.com` domains, but there seems to be some problem with the orders (they remain "pending" seemingly indefinitely). I opened a support ticket with 34sp, but the account is registered to someone else's e-mail address, so I have no way of tracking the progress.

From what I can see, the SSL certificate orders have now all been removed. SSL is a necessity, so we need to chase this down before launching.

If you could speak to the account holder to see if they've received any communication, that would be great.

**Comment by eliascodes** [comment]
@SonjaTwine has the email/password to the 34sp account been changed? I can no longer log in using the credentials in LastPass

**Comment by SonjaTwine** [comment]
Sorry - yes I changed the email to powertochangetwine@gmail.com, since you pointed out that the support emails were going to someone else. Updating on LastPass! (password has not changed)

That URL does certainly not mean anything to me. Could it be so by mistake?
If you want to explain to me how this works later on our call, we can probably work something out?

**Comment by eliascodes** [comment]
Done
