### ISSUE TITLE
Login related user stories

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/hq#4]
After our call today with Frontline, we agreed to generate user stories around users of the app logging in and/or signup up in order to better understand how we can reduce the number of distinct logins users are required to have when using Twine systems.

Put them all here in the replies, and we'll discuss them with Frontline again next week.

**Comment by eliascodes** [comment]
**As a**: CB admin
**I want**: to sign up once and then be able to use all twine applications
**So that**: I don't waste time signing up several times

**As a**: CB admin
**I want**: to use the same login credentials to login to the frontline dashboard, the visitor app and the admin dashboard
**So that**: I don't need to remember multiple login credentials

**As a**: CB admin
**I want**: for changes made to my credentials using one app to be reflected when I log in to any other twine app

**Comment by SonjaTwine** [comment]
As a: PTC superadmin
I want: to set up accounts for new organisations through one interface, not three
So that: I save time and eliminate possibility of human error (i.e. API link between php app and Frontline workspace)

As a: Sector organisation superadmin
I want: to buy a subscription by setting up a new organisation on the superadmin dashboard
So that: I can create new logins without having to manually send details to the Twine team
![screen shot 2018-06-04 at 17 12 23](https://user-images.githubusercontent.com/35500509/40928803-7c9b5e36-681a-11e8-8f9a-6c67d77dc711.png)

**Comment by eliascodes** [comment]
Discussion wrapped up in #6, so this is no longer required.
